### ISSUE TITLE
Поддержка PostgreSQL

### ISSUE THREAD

**Issue by graid2030** [artkost/yii2-qa#16]
Просьба добавить поддержку PostgreSQL. В pg отсутствуют типы enum и tinyint, а также атрибут UNSIGNED.

**Comment by a-komarev** [comment]
=( Грустно, может тогда добавить проверку на тип базы данных? Ведь UNSIGNED для MySQL это правильное решение.
```
if ($this->db->driverName === 'mysql') {
```

**Comment by JiLiZART** [comment]
Возможно

**Comment by graid2030** [comment]
2 147 483 647 вроде более чем достаточно должно быть, а вот чего я действительно не учел так это миграцию с ENUM на SMALLINT для тех у кого установлен модуль был уже. Извиняюсь первый коммит в опенсорс проект мой.

**Comment by JiLiZART** [comment]
Никогда не поздно исправится :)

**Comment by a-komarev** [comment]
Вопрос больше не в запасе значений, а в том что модель не подразумевает отрицательные значения в этих полях, и UNSIGNED явно отражает это. В любом случае это не критично.
