### ISSUE TITLE
error migrate in postgresql

### ISSUE THREAD

**Issue by xaxel** [artkost/yii2-qa#19]
I'm working with postgres database and when I try to migrate to any of the following lines :

php yii migrate/up --migrationPath=@vendor/artkost/yii2-qa/migrations

yii migrate/up --migrationPath=@vendor/artkost/yii2-qa/migrations

./yii migrate/up --migrationPath=@vendor/artkost/yii2-qa/migrations

I get the following error:
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\console\ErrorHandler::errorAction'

**Comment by JiLiZART** [comment]
I installed `yii2-app-basic` boilerplate.
Then i use `php composer.phar require "artkost/yii2-qa"`
After i install migrations.
```sh
php yii migrate/up --migrationPath=@vendor/artkost/yii2-qa/migrations
Yii Migration Tool (based on Yii v2.0.4-dev)

Creating migration history table "migration"...Done.
Total 5 new migrations to be applied:
	m140314_120159_create_qa_question_table
	m140314_120441_create_qa_answer_table
	m140314_120505_create_qa_tag_table
	m140316_070048_create_qa_vote_table
	m140512_191636_create_qa_favorite_table

Apply the above migrations? (yes|no) [no]:yes
*** applying m140314_120159_create_qa_question_table
    > create table {{%qa_question}} ... done (time: 0.102s)
*** applied m140314_120159_create_qa_question_table (time: 0.116s)

*** applying m140314_120441_create_qa_answer_table
    > create table qa_answer ... done (time: 0.050s)
*** applied m140314_120441_create_qa_answer_table (time: 0.059s)

*** applying m140314_120505_create_qa_tag_table
    > create table qa_tag ... done (time: 0.041s)
*** applied m140314_120505_create_qa_tag_table (time: 0.050s)

*** applying m140316_070048_create_qa_vote_table
    > create table qa_vote ... done (time: 0.033s)
*** applied m140316_070048_create_qa_vote_table (time: 0.042s)

*** applying m140512_191636_create_qa_favorite_table
    > create table qa_favorite ... done (time: 0.033s)
*** applied m140512_191636_create_qa_favorite_table (time: 0.042s)


Migrated up successfully.
```

My db config
```php
return [
    'class' => 'yii\db\Connection',
    'dsn' => 'pgsql:host=localhost;dbname=yii2qatest',
    'username' => 'root',
    'password' => 'password',
    'charset' => 'utf8',
    'schemaMap' => [
    	'pgsql' => [
    		'class' => 'yii\db\pgsql\Schema',
    		'defaultSchema' => 'public'
    	]
    ]
];
```

Can you provide more information about your configuration ?

**Comment by xaxel** [comment]
My db config
'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'pgsql:host=localhost;dbname=yattsi',
            'username' => 'postgres',
            'password' => 'password ',
            'charset' => 'utf8',
        ],

I installed advanced template

**Comment by JiLiZART** [comment]
Okay, i will try advanced

**Comment by robregonm** [comment]
Tried both: basic and advanced and worked fine. I think you should check your Yii version in composer (just update using composer).
Any further issues?

**Comment by chitwarnold** [comment]
the issues is with the migrations script it is meant to work with mysql only. {app_base_url}/console/migrations/*.php does not have an else : pgsql, it only has if for mysql
