### ISSUE TITLE
DI container error

### ISSUE THREAD

**Issue by a-komarev** [artkost/yii2-qa#21]
I haven't upgraded your extenstion for a long time. After upgrading I'm getting an error in backend application, but there is no app configured in it:
```
Missing required parameter "id" when instantiating "artkost\qa\Module".
```

In frontend's config I've got:
```
    'modules' => [
        'qa' => [
            'class' => 'artkost\qa\Module',
            'userClass' => 'common\models\User',
            'userNameFormatter' => 'getUsername'
        ],
    ],
```

**Comment by a-komarev** [comment]
Reverted back to `"artkost/yii2-qa": "0.2",` while it isn't fixed.

**Comment by JiLiZART** [comment]
Yes i know about this problem, soon i fix it

**Comment by JiLiZART** [comment]
Fixed in https://github.com/artkost/yii2-qa/commit/a44008f5a323bd4577d0f1e8803b3a2ca039fd89
