### ISSUE TITLE
string2Array

### ISSUE THREAD

**Issue by ShNURoK42** [artkost/yii2-qa#32]
Hi,

why you do not use `explode()` in https://github.com/artkost/yii2-qa/blob/master/models/Tag.php#L47 ?

**Comment by JiLiZART** [comment]
You think `explode` faster ?

**Comment by graid2030** [comment]
Преждевременная оптимизация, explode проще читается. Так-то пофиг конечно.

**Comment by ShNURoK42** [comment]
I don't know, I only ask.

**Comment by JiLiZART** [comment]
If it realy matter i cant change implementation.
