### ISSUE TITLE
Cannot instantiate interface artkost\qa\models\QuestionInterface

### ISSUE THREAD

**Issue by MrAwanishKumar** [artkost/yii2-qa#36]
Hi,

When clicking on active question title - it giving error say "Cannot instantiate interface artkost\qa\models\QuestionInterface".

Where is the issued, I could not figure out. Need help here.

Thanks

**Comment by JiLiZART** [comment]
Thank you for reporting this issue, currenlty master and develop branches are unstable, can you use any tag varsions? Just point `0.3.7` in your dependency.

**Comment by MrAwanishKumar** [comment]
Thank you, will try the same.
